### ISSUE TITLE
KVRocks cluster slave metrics not scraped

### ISSUE THREAD

**Issue by pk-vungle** [RocksLabs/kvrocks_exporter#24]
**Describe the problem**
I have a kvrocks cluster with 4 nodes, 2 of which are masters node and one replica connected to respective masters. Kvrocks exporter is installed on all nodes and the scrape config is such:

```
      - job_name: kvrocks_exporter_stage_kafka_targets
        static_configs:
          - targets:
            - kvrocks://kvrocks-1001:6379
            - kvrocks://kvrocks-1002:6379
            - kvrocks://kvrocks-1003:6379
            - kvrocks://kvrocks-1004:6379
        metrics_path: /scrape
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: kvrocks-1001:9121
```
The kvrocks_exporter are started as such
```
/usr/local/bin/kvrocks_exporter -kvrocks.addr kvrocks://localhost:6379 -include-system-metrics -is-cluster
```

From prometheus, the metrics from master nodes, 1001 and 1002 are available. However, 1003 and 1004 which are the slaves nodes, metrics are not showing. Metrics browser are only showing these metrics for 1003 and 1004

![image](https://github.com/RocksLabs/kvrocks_exporter/assets/19474270/df98509f-6032-4177-80a9-27115380307e)

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[/] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
```
/usr/local/bin/kvrocks_exporter -kvrocks.addr kvrocks://localhost:6379 -include-system-metrics -is-cluster
```

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

I should be able to see all metrics from each nodes.

**Screenshots**

**Additional context**
