### ISSUE TITLE
kvrocks kvrocks_db_keys_expired and kvrocks_db_keys_expiring Unable to obtain data

### ISSUE THREAD

**Issue by mansoncui** [RocksLabs/kvrocks_exporter#67]
ubuntu22
kvrocks_exporter 1.0.8
kvrocks version 2.11.1

prometheus kvrocks config job:
```
scrape_configs:
  ## config for the multiple kvrocks targets that the exporter will scrape
  - job_name: 'kvrocks_exporter_targets_master'
    static_configs:
      - targets:
        - kvrocks://10.xxxx:6666
        - kvrocks://10.xxxx:6666
        - kvrocks://10.xxxx:6666
        - kvrocks://10.xxxx:6667
        - kvrocks://10.xxxx:6667
        - kvrocks://10.xxxx:6667
        - kvrocks://10.xxxx:6668
        - kvrocks://10.xxxx:6668
        - kvrocks://10.xxxx:6668
        - kvrocks://10.xxxx:6669
        - kvrocks://10.xxxx:6669
        - kvrocks://10.xxxx:6669
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.xxxx:9121
```
<img width="1356" alt="Image" src="https://github.com/user-attachments/assets/aeedd0d6-fc04-41e7-aaa6-0d184f19081e" />

<img width="1339" alt="Image" src="https://github.com/user-attachments/assets/3f15150f-162c-485f-953c-97f8c4865771" />
